apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mockery
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: dev
  chart:
    spec:
      chart: mockery
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: ghcr-mockery
        namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
