apiVersion: v1
kind: Namespace
metadata:
  name: monitor
  labels:
    istoio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-ingress
