apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-ingress
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: istio-ingress
  dependsOn:
    - name: istiod
      namespace: flux-system
  chart:
    spec:
      chart: gateway
      version: "1.26.4"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  install:
    disableSchemaValidation: true
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    disableSchemaValidation: true
    remediation:
      retries: 3
  values:
    # Namespace labels are managed by namespace.yaml in kustomization
    service:
      type: LoadBalancer
      ports:
        - name: status-port
          port: 15021
          protocol: TCP
          targetPort: 15021
        - name: http2
          port: 80
          protocol: TCP
          targetPort: 80
        - name: https
          port: 443
          protocol: TCP
          targetPort: 443
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 2000m
        memory: 1024Mi
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 5
      targetCPUUtilizationPercentage: 80
