apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-base
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: istio-system
  chart:
    spec:
      chart: base
      version: "1.24.0"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  install:
    createNamespace: false # We create it explicitly
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
