apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: istio-system
  dependsOn:
    - name: istio-base
      namespace: flux-system
  chart:
    spec:
      chart: istiod
      version: "1.24.0"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    global:
      proxy:
        privileged: true